### ISSUE TITLE
Sort branches by activity

### ISSUE THREAD

**Issue by upsj** [pse-parkview/PSE_dashboard#112]
At the moment, branches are sorted alphabetically, which makes it difficult to jump to the most recent changes. It might be useful to sort them by the date of their most recent commit, or some similar heuristic for what "active" means, maybe also differentiating between "active" and "stale" branches (let's say older than 1 month), and/or pinning `master` and `develop` to the top.

Github provides this information in their GUI ([example](https://github.com/ginkgo-project/ginkgo/branches/active)), but it looks like they cannot be queried via the API ([discussion](https://github.community/t/github-api-v3-to-list-active-branches-only/14371)).

**Comment by taDachs** [comment]
We could simply disable sorting (if it exists somewhere) and sort the branches in the script that collects the git data for the parkview-data repo by the date of the latest commit

**Comment by taDachs** [comment]
implemented in https://github.com/pse-parkview/parkview-data/commit/5a1314e7c6c3facdf7c6fc68252c9fa777999362
