### ISSUE TITLE
Investigate static site generation

### ISSUE THREAD

**Issue by upsj** [pse-parkview/PSE_dashboard#115]
Could the whole backend be turned into a static site generator, so it can be uploaded to a github.io page?
This would eliminate the need for a separate server, and almost all security concerns that might come with it.

**Comment by taDachs** [comment]
While it can be turned into a static site generator, I don't think it can be used with github pages. As far as I know github pages supports only html/css/Javascript and the backend would use kotlin/spring.

**Comment by upsj** [comment]
My idea here was that instead of dynamically generating JSON responses, we precompute the data for all benchmark types (or move more responsibility to the frontend) and push it to a Github Page. That would not require any Spring interaction.

**Comment by taDachs** [comment]
So you would run a benchmark, take results, and compute the data for every plot type and upload that to the pages repository? Also all features from the backend would have to be moved to the frontend.

**Comment by taDachs** [comment]
We technically only really need the git handler part tho, that one should be fairly easy to move to the frontend. I have also read [somewhere](https://kotlinlang.org/docs/js-overview.html) and [somewhere else](https://dev.to/kotlin/hosting-kotlin-js-on-github-pages-via-github-actions-3gep) that kotlin is compatible with github pages. That would mean we could actually reuse some of the backend code and wouldn't really have to rewrite it for the frontend. The webhook for tracking the performance could be implemented with github actions.

**Comment by taDachs** [comment]
[site](https://pse-parkview.github.io/Parkview/) is up, but not yet fully working
