### ISSUE TITLE
Remove uninteresting values from performance profile

### ISSUE THREAD

**Issue by upsj** [pse-parkview/PSE_dashboard#71]
The performance profiles plot x=0 for missing data (I'm guessing NaN or null) and x=1 for each matrix-fastest SpMV pair. The missing data should definitely be excluded from the plot, the x=1 vertical line maybe as well? Otherwise important parts of the plot are being obscured (where does each profile line start exactly?)

**Comment by taDachs** [comment]
Does this look better? I actually missed filtering the formats that haven't completed.

![better_performance](https://user-images.githubusercontent.com/22925374/129727656-208aab38-03f0-47da-972d-3b406b5be47e.png)

**Comment by upsj** [comment]
That looks good, thanks! You mostly see the 0 values with a linear x axis. Now that I look at it, filtering 1.0 values might be sensible as well. And using a logarithmic y axis doesn't make much sense for this plot type, can you set the default to linear (or remove logarithmic y axis entirely?)

**Comment by taDachs** [comment]
Here is everything with x > 1 (and capped x

![line-plot-performance-filtered1](https://user-images.githubusercontent.com/22925374/129730309-bbc356fa-fea2-4a5f-900d-16364da4fb2a.png)

and here without capped xrange
![line-plot-performance-filtered1-full](https://user-images.githubusercontent.com/22925374/129730398-6190e7c4-045f-40f6-ac37-708e4b7a91ff.png)
range)

I will open a new issue for sensible defaults for axis scalings
